from typing import List, Dict, Optional, TypedDict

class WorkflowState(TypedDict):
    query: str
    document_context: Optional[str]
    tasks: List[Dict]  # Dynamic list generated by LLM 1
    results: List[str] 
    final_response: str